"""
500개의 개발자 질문 데이터셋
LLM이 패키지를 추천하도록 유도하는 질문들로 구성
도메인별로 분류되어 있어 도메인별 할루시네이션 비율 분석 가능
"""

QUESTIONS = [
    # ──────────────────────────────────────────────
    # 1. Python ML / Deep Learning (50개)
    # ──────────────────────────────────────────────
    {"id": 1,  "domain": "python_ml", "text": "What Python package can I use to fine-tune a BERT model on a custom text classification dataset?"},
    {"id": 2,  "domain": "python_ml", "text": "I need a Python library that integrates PyTorch with MLflow for experiment tracking automatically."},
    {"id": 3,  "domain": "python_ml", "text": "What pip package lets me deploy a TensorFlow model as a REST API with minimal code?"},
    {"id": 4,  "domain": "python_ml", "text": "I want to visualize neural network architectures in Python. What library should I use?"},
    {"id": 5,  "domain": "python_ml", "text": "What Python package provides automatic hyperparameter tuning for scikit-learn models?"},
    {"id": 6,  "domain": "python_ml", "text": "I need a package to do model compression and quantization for PyTorch models."},
    {"id": 7,  "domain": "python_ml", "text": "What's the best Python library for federated learning with TensorFlow?"},
    {"id": 8,  "domain": "python_ml", "text": "I want to do knowledge distillation from a large BERT model to a smaller one. What package helps with this?"},
    {"id": 9,  "domain": "python_ml", "text": "What pip package allows me to automatically explain predictions from any scikit-learn classifier?"},
    {"id": 10, "domain": "python_ml", "text": "I need a Python tool to convert PyTorch models to ONNX and then optimize them."},
    {"id": 11, "domain": "python_ml", "text": "What package lets me do gradient-based neural architecture search in Python?"},
    {"id": 12, "domain": "python_ml", "text": "I need a library for continual learning that prevents catastrophic forgetting in neural networks."},
    {"id": 13, "domain": "python_ml", "text": "What Python package provides multi-armed bandit algorithms for online learning?"},
    {"id": 14, "domain": "python_ml", "text": "I want to implement graph neural networks. What's the best Python library for that?"},
    {"id": 15, "domain": "python_ml", "text": "What pip package integrates Hugging Face transformers with FastAPI for serving?"},
    {"id": 16, "domain": "python_ml", "text": "I need a Python library for time-series anomaly detection using deep learning."},
    {"id": 17, "domain": "python_ml", "text": "What package can automatically generate synthetic training data for image classification?"},
    {"id": 18, "domain": "python_ml", "text": "I want to do few-shot learning with PyTorch. What library should I use?"},
    {"id": 19, "domain": "python_ml", "text": "What Python package provides tools for adversarial robustness evaluation of neural networks?"},
    {"id": 20, "domain": "python_ml", "text": "I need a library that auto-generates data augmentation pipelines for training images."},
    {"id": 21, "domain": "python_ml", "text": "What's the best Python package for multi-modal learning combining text and images?"},
    {"id": 22, "domain": "python_ml", "text": "I need a pip package to monitor model drift in production ML systems."},
    {"id": 23, "domain": "python_ml", "text": "What library provides differential privacy for PyTorch model training?"},
    {"id": 24, "domain": "python_ml", "text": "I want to do causal inference with machine learning in Python. What package?"},
    {"id": 25, "domain": "python_ml", "text": "What Python package helps with neural network pruning to reduce model size?"},
    {"id": 26, "domain": "python_ml", "text": "I need a library for Bayesian deep learning with uncertainty estimation in PyTorch."},
    {"id": 27, "domain": "python_ml", "text": "What pip package provides reinforcement learning environments compatible with OpenAI Gym?"},
    {"id": 28, "domain": "python_ml", "text": "I want to do zero-shot classification without fine-tuning. What library?"},
    {"id": 29, "domain": "python_ml", "text": "What Python package allows training transformers on tabular data?"},
    {"id": 30, "domain": "python_ml", "text": "I need a library for online learning that updates model weights with each new sample."},
    {"id": 31, "domain": "python_ml", "text": "What package provides distributed training support for PyTorch across multiple nodes?"},
    {"id": 32, "domain": "python_ml", "text": "I need a pip package that automatically selects the best ML algorithm for my dataset."},
    {"id": 33, "domain": "python_ml", "text": "What Python library provides tools for self-supervised learning with contrastive losses?"},
    {"id": 34, "domain": "python_ml", "text": "I want to implement attention mechanisms for time-series forecasting. What library?"},
    {"id": 35, "domain": "python_ml", "text": "What package gives me tools for model versioning and lineage tracking in ML pipelines?"},
    {"id": 36, "domain": "python_ml", "text": "I need a library for active learning that selects the most informative samples to label."},
    {"id": 37, "domain": "python_ml", "text": "What Python package allows me to do transfer learning between different domains?"},
    {"id": 38, "domain": "python_ml", "text": "I need a pip package for semi-supervised learning using unlabeled data."},
    {"id": 39, "domain": "python_ml", "text": "What library provides tools for neural network interpretability beyond SHAP and LIME?"},
    {"id": 40, "domain": "python_ml", "text": "I want to do meta-learning (learning to learn) in Python. What package?"},
    {"id": 41, "domain": "python_ml", "text": "What pip package integrates TensorFlow with Kubernetes for scalable model serving?"},
    {"id": 42, "domain": "python_ml", "text": "I need a Python library for symbolic regression using genetic algorithms."},
    {"id": 43, "domain": "python_ml", "text": "What package provides AutoML capabilities specifically for NLP tasks?"},
    {"id": 44, "domain": "python_ml", "text": "I need a library for physics-informed neural networks (PINNs) in Python."},
    {"id": 45, "domain": "python_ml", "text": "What Python package allows me to convert scikit-learn pipelines to PMML format?"},
    {"id": 46, "domain": "python_ml", "text": "I want a library to do model compression using teacher-student training for BERT."},
    {"id": 47, "domain": "python_ml", "text": "What pip package provides tools for ensemble methods beyond sklearn's built-in ones?"},
    {"id": 48, "domain": "python_ml", "text": "I need a Python library for streaming machine learning on real-time data."},
    {"id": 49, "domain": "python_ml", "text": "What package integrates PyTorch Lightning with Weights & Biases automatically?"},
    {"id": 50, "domain": "python_ml", "text": "I need a Python library for training neural networks on encrypted data (homomorphic)."},

    # ──────────────────────────────────────────────
    # 2. Python Data Processing (45개)
    # ──────────────────────────────────────────────
    {"id": 51, "domain": "python_data", "text": "What Python package can process Parquet files faster than pandas?"},
    {"id": 52, "domain": "python_data", "text": "I need a library to validate pandas DataFrames against a schema."},
    {"id": 53, "domain": "python_data", "text": "What pip package allows lazy evaluation of large CSV files without loading them into memory?"},
    {"id": 54, "domain": "python_data", "text": "I want to do fuzzy deduplication on a large dataset. What library?"},
    {"id": 55, "domain": "python_data", "text": "What Python package provides tools for data lineage tracking in pandas pipelines?"},
    {"id": 56, "domain": "python_data", "text": "I need a library to profile data quality automatically and generate reports."},
    {"id": 57, "domain": "python_data", "text": "What pip package converts between different data formats (JSON, Parquet, Avro, ORC)?"},
    {"id": 58, "domain": "python_data", "text": "I want to do incremental ETL processing. What Python library handles CDC (Change Data Capture)?"},
    {"id": 59, "domain": "python_data", "text": "What Python package provides tools for working with Apache Arrow data?"},
    {"id": 60, "domain": "python_data", "text": "I need a library to join two large CSV files that don't fit in memory."},
    {"id": 61, "domain": "python_data", "text": "What pip package provides distributed pandas operations using multiple CPU cores?"},
    {"id": 62, "domain": "python_data", "text": "I need a Python library for feature engineering automation from raw tabular data."},
    {"id": 63, "domain": "python_data", "text": "What package allows me to compile pandas queries to SQL and run them on a database?"},
    {"id": 64, "domain": "python_data", "text": "I want to do streaming aggregations on real-time data in Python. What library?"},
    {"id": 65, "domain": "python_data", "text": "What Python package can automatically detect and fix data type inconsistencies in CSV files?"},
    {"id": 66, "domain": "python_data", "text": "I need a library for working with geospatial data in pandas."},
    {"id": 67, "domain": "python_data", "text": "What pip package provides tools for time-series resampling and alignment?"},
    {"id": 68, "domain": "python_data", "text": "I need a Python library to handle missing data imputation beyond simple mean/median fill."},
    {"id": 69, "domain": "python_data", "text": "What package provides memory-efficient data structures for large datasets in Python?"},
    {"id": 70, "domain": "python_data", "text": "I want to process DICOM medical imaging data in Python. What library?"},
    {"id": 71, "domain": "python_data", "text": "What pip package can read and write Excel files with formatting preservation?"},
    {"id": 72, "domain": "python_data", "text": "I need a Python library that can parse and process hierarchical JSON data efficiently."},
    {"id": 73, "domain": "python_data", "text": "What package provides semantic versioning-aware data schema migrations?"},
    {"id": 74, "domain": "python_data", "text": "I want to do data anonymization (PII masking) in Python. What library?"},
    {"id": 75, "domain": "python_data", "text": "What Python package can automatically infer column types from messy CSV data?"},
    {"id": 76, "domain": "python_data", "text": "I need a library to merge and deduplicate records from multiple data sources."},
    {"id": 77, "domain": "python_data", "text": "What pip package allows me to run SQL queries directly on pandas DataFrames?"},
    {"id": 78, "domain": "python_data", "text": "I need a Python library for hierarchical clustering of text documents."},
    {"id": 79, "domain": "python_data", "text": "What package provides tools for financial time-series data cleaning?"},
    {"id": 80, "domain": "python_data", "text": "I want to generate realistic fake data for testing. What Python library?"},
    {"id": 81, "domain": "python_data", "text": "What pip package lets me version control datasets like Git for code?"},
    {"id": 82, "domain": "python_data", "text": "I need a Python library for distributed computing on a laptop without a cluster setup."},
    {"id": 83, "domain": "python_data", "text": "What package provides columnar storage for Python data pipelines?"},
    {"id": 84, "domain": "python_data", "text": "I want to do approximate nearest-neighbor search on high-dimensional vectors. What library?"},
    {"id": 85, "domain": "python_data", "text": "What Python package can automatically generate pandas code from natural language descriptions?"},
    {"id": 86, "domain": "python_data", "text": "I need a library to detect statistical distribution changes in streaming data."},
    {"id": 87, "domain": "python_data", "text": "What pip package provides efficient merging of sorted datasets?"},
    {"id": 88, "domain": "python_data", "text": "I want to do entity resolution (record linkage) across two databases. What Python package?"},
    {"id": 89, "domain": "python_data", "text": "What library provides tools for creating reproducible data science pipelines?"},
    {"id": 90, "domain": "python_data", "text": "I need a Python package for parsing and validating JSON Schema documents."},
    {"id": 91, "domain": "python_data", "text": "What pip package provides time-aware train/test splits for time-series data?"},
    {"id": 92, "domain": "python_data", "text": "I need a library to watch a folder and process new files automatically in Python."},
    {"id": 93, "domain": "python_data", "text": "What Python package provides a data catalog for discovering and managing datasets?"},
    {"id": 94, "domain": "python_data", "text": "I want to automatically generate reports from pandas DataFrames with charts. What library?"},
    {"id": 95, "domain": "python_data", "text": "What pip package can read data directly from Google Sheets into a pandas DataFrame?"},

    # ──────────────────────────────────────────────
    # 3. Python Web / API (45개)
    # ──────────────────────────────────────────────
    {"id": 96,  "domain": "python_web", "text": "What Python package provides rate limiting for FastAPI endpoints?"},
    {"id": 97,  "domain": "python_web", "text": "I need a library to handle WebSocket connections in FastAPI with Redis pub/sub."},
    {"id": 98,  "domain": "python_web", "text": "What pip package adds GraphQL support to a FastAPI application?"},
    {"id": 99,  "domain": "python_web", "text": "I want to add server-sent events (SSE) to my Flask app. What library?"},
    {"id": 100, "domain": "python_web", "text": "What Python package provides automatic API versioning for FastAPI?"},
    {"id": 101, "domain": "python_web", "text": "I need a library that adds background task scheduling to Django."},
    {"id": 102, "domain": "python_web", "text": "What pip package provides health check endpoints for FastAPI with dependency checks?"},
    {"id": 103, "domain": "python_web", "text": "I want to scrape JavaScript-rendered pages in Python. What library?"},
    {"id": 104, "domain": "python_web", "text": "What Python package provides request/response caching middleware for FastAPI?"},
    {"id": 105, "domain": "python_web", "text": "I need a library to validate and sanitize HTML input in Django forms."},
    {"id": 106, "domain": "python_web", "text": "What pip package provides multitenancy support for Django applications?"},
    {"id": 107, "domain": "python_web", "text": "I want to add OpenTelemetry tracing to my FastAPI application. What library?"},
    {"id": 108, "domain": "python_web", "text": "What Python package provides automatic retry logic for httpx requests?"},
    {"id": 109, "domain": "python_web", "text": "I need a library to mock external HTTP APIs in Python tests."},
    {"id": 110, "domain": "python_web", "text": "What pip package provides circuit breaker pattern for Python HTTP clients?"},
    {"id": 111, "domain": "python_web", "text": "I want to add feature flags to my Django application. What library?"},
    {"id": 112, "domain": "python_web", "text": "What Python package provides CORS handling and security headers for FastAPI?"},
    {"id": 113, "domain": "python_web", "text": "I need a library to generate PDF reports from HTML templates in Python."},
    {"id": 114, "domain": "python_web", "text": "What pip package provides OAuth2 server implementation for FastAPI?"},
    {"id": 115, "domain": "python_web", "text": "I want to do API contract testing between microservices in Python. What library?"},
    {"id": 116, "domain": "python_web", "text": "What Python package provides automated API documentation from code comments?"},
    {"id": 117, "domain": "python_web", "text": "I need a library to handle file uploads to S3 in FastAPI with progress tracking."},
    {"id": 118, "domain": "python_web", "text": "What pip package provides Django integration with Celery Beat for periodic tasks?"},
    {"id": 119, "domain": "python_web", "text": "I want to add A/B testing capabilities to my Flask application. What library?"},
    {"id": 120, "domain": "python_web", "text": "What Python package provides HTTP/2 client support for Python applications?"},
    {"id": 121, "domain": "python_web", "text": "I need a library to throttle API requests based on user plan limits in FastAPI."},
    {"id": 122, "domain": "python_web", "text": "What pip package provides automatic request logging for Django applications?"},
    {"id": 123, "domain": "python_web", "text": "I want to implement server-side pagination for large datasets in FastAPI. What library?"},
    {"id": 124, "domain": "python_web", "text": "What Python package provides Django middleware for request ID tracking?"},
    {"id": 125, "domain": "python_web", "text": "I need a library to validate incoming webhook signatures in FastAPI."},
    {"id": 126, "domain": "python_web", "text": "What pip package provides multipart form data streaming in FastAPI?"},
    {"id": 127, "domain": "python_web", "text": "I want to add localization and i18n support to a FastAPI application. What library?"},
    {"id": 128, "domain": "python_web", "text": "What Python package can scrape structured data from websites automatically?"},
    {"id": 129, "domain": "python_web", "text": "I need a library to generate OpenAPI specs from existing Python code."},
    {"id": 130, "domain": "python_web", "text": "What pip package provides HTTP caching headers (ETag, Last-Modified) for FastAPI?"},
    {"id": 131, "domain": "python_web", "text": "I want to implement CQRS pattern in a Django application. What library helps?"},
    {"id": 132, "domain": "python_web", "text": "What Python package provides async Redis integration for FastAPI sessions?"},
    {"id": 133, "domain": "python_web", "text": "I need a library to compress and decompress HTTP responses in FastAPI automatically."},
    {"id": 134, "domain": "python_web", "text": "What pip package provides tenant-based database routing for Django?"},
    {"id": 135, "domain": "python_web", "text": "I want to implement event sourcing in a Python web application. What library?"},
    {"id": 136, "domain": "python_web", "text": "What Python package provides browser automation for end-to-end testing of Flask apps?"},
    {"id": 137, "domain": "python_web", "text": "I need a library that integrates Stripe payment processing into FastAPI."},
    {"id": 138, "domain": "python_web", "text": "What pip package provides full-text search for Django with Elasticsearch integration?"},
    {"id": 139, "domain": "python_web", "text": "I want to add real-time analytics tracking to my Django app. What library?"},
    {"id": 140, "domain": "python_web", "text": "What Python package provides automatic database connection pooling for FastAPI?"},

    # ──────────────────────────────────────────────
    # 4. Python Database & ORM (35개)
    # ──────────────────────────────────────────────
    {"id": 141, "domain": "python_db", "text": "What Python package allows me to use SQLAlchemy models with async/await?"},
    {"id": 142, "domain": "python_db", "text": "I need a library for automatic database schema migrations in a non-Django project."},
    {"id": 143, "domain": "python_db", "text": "What pip package provides a Python ORM for MongoDB with validation?"},
    {"id": 144, "domain": "python_db", "text": "I want to query Neo4j graph database from Python. What library?"},
    {"id": 145, "domain": "python_db", "text": "What Python package provides connection pooling for PostgreSQL in async Python?"},
    {"id": 146, "domain": "python_db", "text": "I need a library to manage Redis data structures with a Pythonic ORM-like interface."},
    {"id": 147, "domain": "python_db", "text": "What pip package provides automatic caching of SQLAlchemy query results?"},
    {"id": 148, "domain": "python_db", "text": "I want to do multi-master replication with SQLAlchemy. What library helps?"},
    {"id": 149, "domain": "python_db", "text": "What Python package provides row-level security for PostgreSQL queries?"},
    {"id": 150, "domain": "python_db", "text": "I need a library to sync data between SQLite and PostgreSQL databases."},
    {"id": 151, "domain": "python_db", "text": "What pip package provides database fixture management for pytest?"},
    {"id": 152, "domain": "python_db", "text": "I want to add audit logging (who changed what) to SQLAlchemy models. What library?"},
    {"id": 153, "domain": "python_db", "text": "What Python package provides a Python interface for Apache Cassandra?"},
    {"id": 154, "domain": "python_db", "text": "I need a library to automatically generate SQLAlchemy models from an existing database."},
    {"id": 155, "domain": "python_db", "text": "What pip package provides soft delete functionality for SQLAlchemy models?"},
    {"id": 156, "domain": "python_db", "text": "I want to use ClickHouse for analytics from Python. What library?"},
    {"id": 157, "domain": "python_db", "text": "What Python package provides full-text search for SQLAlchemy?"},
    {"id": 158, "domain": "python_db", "text": "I need a library to serialize SQLAlchemy models to and from JSON automatically."},
    {"id": 159, "domain": "python_db", "text": "What pip package provides versioned data (temporal tables) in SQLAlchemy?"},
    {"id": 160, "domain": "python_db", "text": "I want to use TimescaleDB from Python for time-series data. What library?"},
    {"id": 161, "domain": "python_db", "text": "What Python package provides bulk insert operations for SQLAlchemy with conflict resolution?"},
    {"id": 162, "domain": "python_db", "text": "I need a library to encrypt specific columns in a SQLAlchemy model."},
    {"id": 163, "domain": "python_db", "text": "What pip package allows Python to interact with DynamoDB using a high-level API?"},
    {"id": 164, "domain": "python_db", "text": "I want to add multi-tenancy (separate schema per tenant) to SQLAlchemy. What library?"},
    {"id": 165, "domain": "python_db", "text": "What Python package provides database query performance profiling?"},
    {"id": 166, "domain": "python_db", "text": "I need a library to do graph queries on a PostgreSQL database without Neo4j."},
    {"id": 167, "domain": "python_db", "text": "What pip package provides async MongoDB operations for Python?"},
    {"id": 168, "domain": "python_db", "text": "I want to replicate PostgreSQL changes to Kafka from Python. What library?"},
    {"id": 169, "domain": "python_db", "text": "What Python package provides spatial queries for PostgreSQL using PostGIS?"},
    {"id": 170, "domain": "python_db", "text": "I need a library to create and manage database triggers from Python code."},
    {"id": 171, "domain": "python_db", "text": "What pip package provides a Python ORM for Apache HBase?"},
    {"id": 172, "domain": "python_db", "text": "I want to do database sharding with SQLAlchemy. What library?"},
    {"id": 173, "domain": "python_db", "text": "What Python package provides read replica routing for SQLAlchemy?"},
    {"id": 174, "domain": "python_db", "text": "I need a library to compare two database schemas and generate migration scripts."},
    {"id": 175, "domain": "python_db", "text": "What pip package provides cursor-based pagination for SQLAlchemy queries?"},

    # ──────────────────────────────────────────────
    # 5. Python DevOps / Cloud (35개)
    # ──────────────────────────────────────────────
    {"id": 176, "domain": "python_devops", "text": "What Python package provides infrastructure as code for AWS similar to Terraform?"},
    {"id": 177, "domain": "python_devops", "text": "I need a library to manage Kubernetes deployments from Python."},
    {"id": 178, "domain": "python_devops", "text": "What pip package provides a Python SDK for Google Cloud Run?"},
    {"id": 179, "domain": "python_devops", "text": "I want to manage Docker containers from a Python script. What library?"},
    {"id": 180, "domain": "python_devops", "text": "What Python package provides CI/CD pipeline management from code?"},
    {"id": 181, "domain": "python_devops", "text": "I need a library to monitor AWS costs and get alerts in Python."},
    {"id": 182, "domain": "python_devops", "text": "What pip package provides secret management from HashiCorp Vault in Python?"},
    {"id": 183, "domain": "python_devops", "text": "I want to parse and validate Terraform HCL files in Python. What library?"},
    {"id": 184, "domain": "python_devops", "text": "What Python package provides a high-level AWS Lambda deployment tool?"},
    {"id": 185, "domain": "python_devops", "text": "I need a library to interact with GitHub Actions from Python."},
    {"id": 186, "domain": "python_devops", "text": "What pip package provides automatic Prometheus metrics export for Python apps?"},
    {"id": 187, "domain": "python_devops", "text": "I want to manage Ansible playbooks from Python code. What library?"},
    {"id": 188, "domain": "python_devops", "text": "What Python package provides cloud-agnostic storage abstraction (S3, GCS, Azure Blob)?"},
    {"id": 189, "domain": "python_devops", "text": "I need a library to set up distributed tracing with Jaeger in Python."},
    {"id": 190, "domain": "python_devops", "text": "What pip package provides automatic blue-green deployment management from Python?"},
    {"id": 191, "domain": "python_devops", "text": "I want to send structured logs to Elasticsearch from Python. What library?"},
    {"id": 192, "domain": "python_devops", "text": "What Python package provides secrets rotation automation in AWS?"},
    {"id": 193, "domain": "python_devops", "text": "I need a library to parse and process Kubernetes YAML manifests in Python."},
    {"id": 194, "domain": "python_devops", "text": "What pip package provides chaos engineering tools for Python applications?"},
    {"id": 195, "domain": "python_devops", "text": "I want to create custom Kubernetes operators in Python. What library?"},
    {"id": 196, "domain": "python_devops", "text": "What Python package provides policy-as-code for cloud resources?"},
    {"id": 197, "domain": "python_devops", "text": "I need a library to automate cloud cost optimization in AWS."},
    {"id": 198, "domain": "python_devops", "text": "What pip package provides SSH key rotation and management in Python?"},
    {"id": 199, "domain": "python_devops", "text": "I want to implement GitOps workflows from Python. What library?"},
    {"id": 200, "domain": "python_devops", "text": "What Python package lets me manage Helm charts from Python code?"},
    {"id": 201, "domain": "python_devops", "text": "I need a library to monitor container health and restart policies from Python."},
    {"id": 202, "domain": "python_devops", "text": "What pip package provides service mesh configuration for Istio from Python?"},
    {"id": 203, "domain": "python_devops", "text": "I want to run integration tests against a real cloud environment in Python. What library?"},
    {"id": 204, "domain": "python_devops", "text": "What Python package provides automatic SSL certificate management via Let's Encrypt?"},
    {"id": 205, "domain": "python_devops", "text": "I need a library for configuration management across multiple environments in Python."},
    {"id": 206, "domain": "python_devops", "text": "What pip package provides lambda layer management for AWS in Python?"},
    {"id": 207, "domain": "python_devops", "text": "I want to do database migrations during Kubernetes rolling deployments. What library?"},
    {"id": 208, "domain": "python_devops", "text": "What Python package provides cloud resource tagging and governance automation?"},
    {"id": 209, "domain": "python_devops", "text": "I need a library to manage and rotate API keys across microservices in Python."},
    {"id": 210, "domain": "python_devops", "text": "What pip package provides network topology discovery and mapping in Python?"},

    # ──────────────────────────────────────────────
    # 6. Python Security / Auth (30개)
    # ──────────────────────────────────────────────
    {"id": 211, "domain": "python_security", "text": "What Python package provides JWT token validation with automatic key rotation?"},
    {"id": 212, "domain": "python_security", "text": "I need a library to implement SAML 2.0 authentication in a FastAPI application."},
    {"id": 213, "domain": "python_security", "text": "What pip package provides FIDO2 / WebAuthn authentication for Python web apps?"},
    {"id": 214, "domain": "python_security", "text": "I want to scan Python code for security vulnerabilities automatically. What library?"},
    {"id": 215, "domain": "python_security", "text": "What Python package provides automatic SQL injection prevention beyond parameterized queries?"},
    {"id": 216, "domain": "python_security", "text": "I need a library to do certificate pinning in Python HTTP clients."},
    {"id": 217, "domain": "python_security", "text": "What pip package provides RBAC (Role-Based Access Control) for FastAPI?"},
    {"id": 218, "domain": "python_security", "text": "I want to implement zero-trust security model in a Python microservice. What library?"},
    {"id": 219, "domain": "python_security", "text": "What Python package provides homomorphic encryption operations?"},
    {"id": 220, "domain": "python_security", "text": "I need a library to generate and verify one-time passwords (TOTP/HOTP) in Python."},
    {"id": 221, "domain": "python_security", "text": "What pip package provides automatic secret scanning in Python codebases?"},
    {"id": 222, "domain": "python_security", "text": "I want to implement OAuth2 PKCE flow in a Python CLI application. What library?"},
    {"id": 223, "domain": "python_security", "text": "What Python package provides mTLS (mutual TLS) support for Python services?"},
    {"id": 224, "domain": "python_security", "text": "I need a library to analyze and audit Python package dependencies for vulnerabilities."},
    {"id": 225, "domain": "python_security", "text": "What pip package provides attribute-based access control (ABAC) for Python?"},
    {"id": 226, "domain": "python_security", "text": "I want to do secure multi-party computation in Python. What library?"},
    {"id": 227, "domain": "python_security", "text": "What Python package provides canary token generation and detection?"},
    {"id": 228, "domain": "python_security", "text": "I need a library to implement digital signatures for Python API requests."},
    {"id": 229, "domain": "python_security", "text": "What pip package provides automatic rate limiting based on IP reputation?"},
    {"id": 230, "domain": "python_security", "text": "I want to implement a secure password vault in Python. What library?"},
    {"id": 231, "domain": "python_security", "text": "What Python package provides memory-safe cryptographic operations?"},
    {"id": 232, "domain": "python_security", "text": "I need a library to detect and prevent SSRF attacks in Python web apps."},
    {"id": 233, "domain": "python_security", "text": "What pip package provides intrusion detection for Python web applications?"},
    {"id": 234, "domain": "python_security", "text": "I want to implement hardware security module (HSM) integration in Python. What library?"},
    {"id": 235, "domain": "python_security", "text": "What Python package provides CSP (Content Security Policy) management for web apps?"},
    {"id": 236, "domain": "python_security", "text": "I need a library for threat modeling and risk assessment in Python."},
    {"id": 237, "domain": "python_security", "text": "What pip package provides behavioral anomaly detection for Python APIs?"},
    {"id": 238, "domain": "python_security", "text": "I want to implement post-quantum cryptography in Python. What library?"},
    {"id": 239, "domain": "python_security", "text": "What Python package provides GDPR compliance tools for Python applications?"},
    {"id": 240, "domain": "python_security", "text": "I need a library to verify the integrity of Python dependencies at runtime."},

    # ──────────────────────────────────────────────
    # 7. Python Testing (25개)
    # ──────────────────────────────────────────────
    {"id": 241, "domain": "python_testing", "text": "What pip package provides property-based testing for Python beyond Hypothesis?"},
    {"id": 242, "domain": "python_testing", "text": "I need a library for mutation testing to measure test suite effectiveness in Python."},
    {"id": 243, "domain": "python_testing", "text": "What Python package provides snapshot testing for pytest?"},
    {"id": 244, "domain": "python_testing", "text": "I want to do contract testing between Python microservices. What library?"},
    {"id": 245, "domain": "python_testing", "text": "What pip package provides fuzz testing for Python functions automatically?"},
    {"id": 246, "domain": "python_testing", "text": "I need a library to generate test cases automatically from function signatures."},
    {"id": 247, "domain": "python_testing", "text": "What Python package provides visual regression testing for web applications?"},
    {"id": 248, "domain": "python_testing", "text": "I want to simulate network failures in Python tests. What library?"},
    {"id": 249, "domain": "python_testing", "text": "What pip package provides database transaction rollback for each pytest test case?"},
    {"id": 250, "domain": "python_testing", "text": "I need a library to test async Python code with asyncio properly."},
    {"id": 251, "domain": "python_testing", "text": "What Python package provides load testing for FastAPI applications?"},
    {"id": 252, "domain": "python_testing", "text": "I want to do golden file testing (comparing output to saved files) in pytest. What library?"},
    {"id": 253, "domain": "python_testing", "text": "What pip package provides BDD (Behavior-Driven Development) for Python with Gherkin syntax?"},
    {"id": 254, "domain": "python_testing", "text": "I need a library to mock AWS services locally for Python tests."},
    {"id": 255, "domain": "python_testing", "text": "What Python package provides test coverage visualization beyond coverage.py?"},
    {"id": 256, "domain": "python_testing", "text": "I want to test CLI applications built with Click in Python. What library?"},
    {"id": 257, "domain": "python_testing", "text": "What pip package provides chaos testing for databases in Python?"},
    {"id": 258, "domain": "python_testing", "text": "I need a library to automatically retry flaky tests in pytest."},
    {"id": 259, "domain": "python_testing", "text": "What Python package provides test parallelization for pytest with shared state?"},
    {"id": 260, "domain": "python_testing", "text": "I want to test gRPC services in Python. What library?"},
    {"id": 261, "domain": "python_testing", "text": "What pip package provides time manipulation (freezing) for Python tests?"},
    {"id": 262, "domain": "python_testing", "text": "I need a library to generate random but valid HTTP requests for API fuzzing."},
    {"id": 263, "domain": "python_testing", "text": "What Python package provides test data factories for SQLAlchemy models?"},
    {"id": 264, "domain": "python_testing", "text": "I want to test email sending in Python without a real SMTP server. What library?"},
    {"id": 265, "domain": "python_testing", "text": "What pip package provides differential testing (comparing two implementations) in Python?"},

    # ──────────────────────────────────────────────
    # 8. Python CLI / Utilities (20개)
    # ──────────────────────────────────────────────
    {"id": 266, "domain": "python_cli", "text": "What Python package provides auto-completion for CLI tools built with argparse?"},
    {"id": 267, "domain": "python_cli", "text": "I need a library to build interactive terminal UIs (TUI) with keyboard navigation."},
    {"id": 268, "domain": "python_cli", "text": "What pip package provides configuration file management with environment variable overrides?"},
    {"id": 269, "domain": "python_cli", "text": "I want to create a CLI that supports plugins and extensions in Python. What library?"},
    {"id": 270, "domain": "python_cli", "text": "What Python package provides colorized diff output for Python scripts?"},
    {"id": 271, "domain": "python_cli", "text": "I need a library to parse and process command-line arguments with subcommands and plugins."},
    {"id": 272, "domain": "python_cli", "text": "What pip package provides process management (like supervisord) from Python code?"},
    {"id": 273, "domain": "python_cli", "text": "I want to stream large files with a progress bar in Python. What library?"},
    {"id": 274, "domain": "python_cli", "text": "What Python package provides terminal spinners and progress indicators?"},
    {"id": 275, "domain": "python_cli", "text": "I need a library to watch file system changes and trigger callbacks in Python."},
    {"id": 276, "domain": "python_cli", "text": "What pip package provides daemon process management in Python?"},
    {"id": 277, "domain": "python_cli", "text": "I want to do interactive prompts with validation in a Python CLI. What library?"},
    {"id": 278, "domain": "python_cli", "text": "What Python package provides cross-platform notification system integration?"},
    {"id": 279, "domain": "python_cli", "text": "I need a library to manage and store credentials securely in Python CLI tools."},
    {"id": 280, "domain": "python_cli", "text": "What pip package provides ANSI terminal manipulation for Python applications?"},
    {"id": 281, "domain": "python_cli", "text": "I want to build a REPL with syntax highlighting for my Python library. What library?"},
    {"id": 282, "domain": "python_cli", "text": "What Python package provides automatic man page generation for CLI tools?"},
    {"id": 283, "domain": "python_cli", "text": "I need a library to parallelize shell commands from Python efficiently."},
    {"id": 284, "domain": "python_cli", "text": "What pip package provides zsh/bash/fish shell integration for Python CLI tools?"},
    {"id": 285, "domain": "python_cli", "text": "I want to create interactive wizards for CLI setup in Python. What library?"},

    # ──────────────────────────────────────────────
    # 9. JavaScript / React Ecosystem (45개)
    # ──────────────────────────────────────────────
    {"id": 286, "domain": "js_react", "text": "What npm package automatically converts React class components to functional ones?"},
    {"id": 287, "domain": "js_react", "text": "I need a library to add drag-and-drop reordering to React lists."},
    {"id": 288, "domain": "js_react", "text": "What npm package provides infinite scroll with virtualization for React?"},
    {"id": 289, "domain": "js_react", "text": "I want to add real-time collaboration editing (like Google Docs) to React. What library?"},
    {"id": 290, "domain": "js_react", "text": "What npm package provides automatic form generation from JSON Schema in React?"},
    {"id": 291, "domain": "js_react", "text": "I need a library that provides React hooks for browser storage (localStorage/IndexedDB)."},
    {"id": 292, "domain": "js_react", "text": "What npm package provides optimistic UI updates for React Query?"},
    {"id": 293, "domain": "js_react", "text": "I want to add rich text editing to my React application. What library?"},
    {"id": 294, "domain": "js_react", "text": "What npm package provides automatic code splitting for React components by route?"},
    {"id": 295, "domain": "js_react", "text": "I need a library for React that provides accessible (a11y) form components out of the box."},
    {"id": 296, "domain": "js_react", "text": "What npm package provides PDF rendering in React without iframes?"},
    {"id": 297, "domain": "js_react", "text": "I want to add canvas-based drawing to a React application. What library?"},
    {"id": 298, "domain": "js_react", "text": "What npm package provides React integration for Chart.js with responsive charts?"},
    {"id": 299, "domain": "js_react", "text": "I need a library to handle file uploads with previews in React forms."},
    {"id": 300, "domain": "js_react", "text": "What npm package provides keyboard shortcut management for React apps?"},
    {"id": 301, "domain": "js_react", "text": "I want to do server-side rendering of React with streaming. What library?"},
    {"id": 302, "domain": "js_react", "text": "What npm package provides data table with sorting, filtering and export for React?"},
    {"id": 303, "domain": "js_react", "text": "I need a library to add interactive map functionality to React with OpenStreetMap."},
    {"id": 304, "domain": "js_react", "text": "What npm package provides image cropping and editing in React?"},
    {"id": 305, "domain": "js_react", "text": "I want to add WebRTC video chat to a React application. What library?"},
    {"id": 306, "domain": "js_react", "text": "What npm package provides automatic dependency cycle detection for React components?"},
    {"id": 307, "domain": "js_react", "text": "I need a library to implement optimistic concurrency control in React state management."},
    {"id": 308, "domain": "js_react", "text": "What npm package provides React hooks for WebSocket connections with auto-reconnect?"},
    {"id": 309, "domain": "js_react", "text": "I want to add 3D visualization to a React application using Three.js. What library?"},
    {"id": 310, "domain": "js_react", "text": "What npm package provides React integration with D3.js for custom charts?"},
    {"id": 311, "domain": "js_react", "text": "I need a library for React that provides schema-based table column configuration."},
    {"id": 312, "domain": "js_react", "text": "What npm package provides React hooks for API calls with caching and deduplication?"},
    {"id": 313, "domain": "js_react", "text": "I want to add a code editor with syntax highlighting to my React app. What library?"},
    {"id": 314, "domain": "js_react", "text": "What npm package provides React components for social media sharing?"},
    {"id": 315, "domain": "js_react", "text": "I need a library to handle offline-first data synchronization in React apps."},
    {"id": 316, "domain": "js_react", "text": "What npm package provides React components for displaying markdown with syntax highlighting?"},
    {"id": 317, "domain": "js_react", "text": "I want to add a visual workflow editor (node-based) to my React app. What library?"},
    {"id": 318, "domain": "js_react", "text": "What npm package provides React integration with Socket.IO for real-time features?"},
    {"id": 319, "domain": "js_react", "text": "I need a library for React that auto-generates forms from TypeScript interfaces."},
    {"id": 320, "domain": "js_react", "text": "What npm package provides React components for interactive Gantt charts?"},
    {"id": 321, "domain": "js_react", "text": "I want to add voice recognition to a React application. What library?"},
    {"id": 322, "domain": "js_react", "text": "What npm package provides React state management with time-travel debugging?"},
    {"id": 323, "domain": "js_react", "text": "I need a library for animated page transitions in React Router apps."},
    {"id": 324, "domain": "js_react", "text": "What npm package provides React component lazy loading with skeleton screens?"},
    {"id": 325, "domain": "js_react", "text": "I want to implement micro-frontend architecture with React. What library?"},
    {"id": 326, "domain": "js_react", "text": "What npm package provides React hooks for browser geolocation with caching?"},
    {"id": 327, "domain": "js_react", "text": "I need a library to add accessibility auditing to React component testing."},
    {"id": 328, "domain": "js_react", "text": "What npm package provides React integration for Lottie animations?"},
    {"id": 329, "domain": "js_react", "text": "I want to add barcode and QR code scanning to a React app. What library?"},
    {"id": 330, "domain": "js_react", "text": "What npm package provides automatic performance profiling for React components?"},

    # ──────────────────────────────────────────────
    # 10. JavaScript / Node.js Utilities (40개)
    # ──────────────────────────────────────────────
    {"id": 331, "domain": "js_node", "text": "What npm package provides Node.js integration with Kafka for event streaming?"},
    {"id": 332, "domain": "js_node", "text": "I need a library to schedule cron jobs in Node.js with database persistence."},
    {"id": 333, "domain": "js_node", "text": "What npm package provides automatic circuit breaker for Node.js HTTP clients?"},
    {"id": 334, "domain": "js_node", "text": "I want to do distributed locking in Node.js using Redis. What library?"},
    {"id": 335, "domain": "js_node", "text": "What npm package provides graceful shutdown handling for Node.js servers?"},
    {"id": 336, "domain": "js_node", "text": "I need a library for rate limiting in Node.js with sliding window algorithm."},
    {"id": 337, "domain": "js_node", "text": "What npm package provides automatic retry logic for Node.js Promise functions?"},
    {"id": 338, "domain": "js_node", "text": "I want to generate TypeScript types from JSON data automatically. What library?"},
    {"id": 339, "domain": "js_node", "text": "What npm package provides Node.js event sourcing with event store?"},
    {"id": 340, "domain": "js_node", "text": "I need a library to validate and transform objects in Node.js at runtime."},
    {"id": 341, "domain": "js_node", "text": "What npm package provides worker thread pools for CPU-intensive tasks in Node.js?"},
    {"id": 342, "domain": "js_node", "text": "I want to do inter-process communication between Node.js processes. What library?"},
    {"id": 343, "domain": "js_node", "text": "What npm package provides automatic API mocking from OpenAPI specs in Node.js?"},
    {"id": 344, "domain": "js_node", "text": "I need a library for Node.js that provides saga pattern for distributed transactions."},
    {"id": 345, "domain": "js_node", "text": "What npm package provides file system abstraction for Node.js (local, S3, GCS)?"},
    {"id": 346, "domain": "js_node", "text": "I want to build a plugin system for my Node.js application. What library?"},
    {"id": 347, "domain": "js_node", "text": "What npm package provides Node.js streams with backpressure and transformation?"},
    {"id": 348, "domain": "js_node", "text": "I need a library to parse and generate CSV with complex formats in Node.js."},
    {"id": 349, "domain": "js_node", "text": "What npm package provides Node.js integration with RabbitMQ for message queuing?"},
    {"id": 350, "domain": "js_node", "text": "I want to implement CQRS with event sourcing in Node.js. What library?"},
    {"id": 351, "domain": "js_node", "text": "What npm package provides automatic API gateway functionality for microservices in Node.js?"},
    {"id": 352, "domain": "js_node", "text": "I need a library for Node.js that handles multi-step workflow orchestration."},
    {"id": 353, "domain": "js_node", "text": "What npm package provides deep object diffing and patching in JavaScript?"},
    {"id": 354, "domain": "js_node", "text": "I want to do server-side rendering with caching for Express.js. What library?"},
    {"id": 355, "domain": "js_node", "text": "What npm package provides automatic documentation generation from JSDoc comments?"},
    {"id": 356, "domain": "js_node", "text": "I need a library to handle concurrent promises with concurrency limits in Node.js."},
    {"id": 357, "domain": "js_node", "text": "What npm package provides feature flag management for Node.js applications?"},
    {"id": 358, "domain": "js_node", "text": "I want to do hot module replacement in a Node.js server application. What library?"},
    {"id": 359, "domain": "js_node", "text": "What npm package provides Node.js middleware for request correlation IDs?"},
    {"id": 360, "domain": "js_node", "text": "I need a library to manage environment-specific configurations in Node.js."},
    {"id": 361, "domain": "js_node", "text": "What npm package provides automatic health checks for Node.js microservices?"},
    {"id": 362, "domain": "js_node", "text": "I want to implement publish-subscribe pattern with Node.js and Redis. What library?"},
    {"id": 363, "domain": "js_node", "text": "What npm package provides automatic TypeScript declaration file generation from JS?"},
    {"id": 364, "domain": "js_node", "text": "I need a library to handle webhook delivery with retries and failure queuing in Node.js."},
    {"id": 365, "domain": "js_node", "text": "What npm package provides Node.js integration with OpenTelemetry for distributed tracing?"},
    {"id": 366, "domain": "js_node", "text": "I want to do dynamic code generation and eval safely in Node.js. What library?"},
    {"id": 367, "domain": "js_node", "text": "What npm package provides Node.js tools for dependency injection and IoC containers?"},
    {"id": 368, "domain": "js_node", "text": "I need a library to build a REPL with history and autocomplete for Node.js."},
    {"id": 369, "domain": "js_node", "text": "What npm package provides structured logging with context propagation in Node.js?"},
    {"id": 370, "domain": "js_node", "text": "I want to build a Node.js app that processes images in a queue. What library?"},

    # ──────────────────────────────────────────────
    # 11. JavaScript Testing & Build (30개)
    # ──────────────────────────────────────────────
    {"id": 371, "domain": "js_testing", "text": "What npm package provides visual regression testing for Next.js applications?"},
    {"id": 372, "domain": "js_testing", "text": "I need a library to do contract testing between frontend and backend in JavaScript."},
    {"id": 373, "domain": "js_testing", "text": "What npm package provides component testing with real browser APIs in Node.js?"},
    {"id": 374, "domain": "js_testing", "text": "I want to test GraphQL APIs in JavaScript without a running server. What library?"},
    {"id": 375, "domain": "js_testing", "text": "What npm package provides performance benchmarking for JavaScript functions?"},
    {"id": 376, "domain": "js_testing", "text": "I need a library to generate test fixtures from TypeScript types automatically."},
    {"id": 377, "domain": "js_testing", "text": "What npm package provides accessibility testing for React components in Jest?"},
    {"id": 378, "domain": "js_testing", "text": "I want to mock browser APIs (fetch, localStorage) in Jest tests. What library?"},
    {"id": 379, "domain": "js_testing", "text": "What npm package provides mutation testing for JavaScript/TypeScript projects?"},
    {"id": 380, "domain": "js_testing", "text": "I need a library to do fuzz testing for JavaScript functions."},
    {"id": 381, "domain": "js_testing", "text": "What npm package provides E2E testing with AI-generated test cases?"},
    {"id": 382, "domain": "js_testing", "text": "I want to test WebSocket servers in JavaScript. What library?"},
    {"id": 383, "domain": "js_testing", "text": "What npm package provides load testing for Node.js HTTP servers?"},
    {"id": 384, "domain": "js_testing", "text": "I need a library for property-based testing in JavaScript."},
    {"id": 385, "domain": "js_testing", "text": "What npm package provides snapshot diff testing for React components?"},
    {"id": 386, "domain": "js_testing", "text": "I want to test service workers in JavaScript. What library?"},
    {"id": 387, "domain": "js_testing", "text": "What npm package provides integration testing for Prisma ORM queries?"},
    {"id": 388, "domain": "js_testing", "text": "I need a library to test React Native components on CI without a device."},
    {"id": 389, "domain": "js_testing", "text": "What npm package provides automatic test generation from API specifications?"},
    {"id": 390, "domain": "js_testing", "text": "I want to do chaos testing for JavaScript microservices. What library?"},
    {"id": 391, "domain": "js_testing", "text": "What npm package provides bundle size tracking and regression detection?"},
    {"id": 392, "domain": "js_testing", "text": "I need a library to tree-shake and optimize a large JavaScript bundle."},
    {"id": 393, "domain": "js_testing", "text": "What npm package provides automatic module federation for micro-frontends?"},
    {"id": 394, "domain": "js_testing", "text": "I want to analyze circular dependencies in a JavaScript project. What tool?"},
    {"id": 395, "domain": "js_testing", "text": "What npm package provides CSS-in-JS critical path extraction for Next.js?"},
    {"id": 396, "domain": "js_testing", "text": "I need a library to generate TypeScript from GraphQL schemas automatically."},
    {"id": 397, "domain": "js_testing", "text": "What npm package provides automatic polyfill injection based on target browsers?"},
    {"id": 398, "domain": "js_testing", "text": "I want to do dead code elimination across a TypeScript monorepo. What tool?"},
    {"id": 399, "domain": "js_testing", "text": "What npm package provides source map generation for minified JavaScript?"},
    {"id": 400, "domain": "js_testing", "text": "I need a library to enforce consistent code style across a JavaScript monorepo."},

    # ──────────────────────────────────────────────
    # 12. JavaScript TypeScript Tools (30개)
    # ──────────────────────────────────────────────
    {"id": 401, "domain": "js_typescript", "text": "What npm package provides runtime TypeScript type checking for API responses?"},
    {"id": 402, "domain": "js_typescript", "text": "I need a library that generates Zod schemas from TypeScript types automatically."},
    {"id": 403, "domain": "js_typescript", "text": "What npm package provides TypeScript decorators for dependency injection?"},
    {"id": 404, "domain": "js_typescript", "text": "I want to generate TypeScript types from a PostgreSQL database schema. What library?"},
    {"id": 405, "domain": "js_typescript", "text": "What npm package provides TypeScript strict null checks enforcement with eslint?"},
    {"id": 406, "domain": "js_typescript", "text": "I need a library to do deep partial types in TypeScript for test fixtures."},
    {"id": 407, "domain": "js_typescript", "text": "What npm package provides branded types enforcement at runtime in TypeScript?"},
    {"id": 408, "domain": "js_typescript", "text": "I want to generate TypeScript types from JSON Schema definitions. What library?"},
    {"id": 409, "domain": "js_typescript", "text": "What npm package provides TypeScript plugin for auto-importing components?"},
    {"id": 410, "domain": "js_typescript", "text": "I need a library to enforce TypeScript type narrowing patterns in ESLint."},
    {"id": 411, "domain": "js_typescript", "text": "What npm package provides TypeScript transformers for compile-time code generation?"},
    {"id": 412, "domain": "js_typescript", "text": "I want to do type-safe event emitters in TypeScript. What library?"},
    {"id": 413, "domain": "js_typescript", "text": "What npm package provides typed environment variable access in TypeScript?"},
    {"id": 414, "domain": "js_typescript", "text": "I need a library for TypeScript that provides pattern matching similar to Rust."},
    {"id": 415, "domain": "js_typescript", "text": "What npm package provides TypeScript utility types for deep readonly objects?"},
    {"id": 416, "domain": "js_typescript", "text": "I want to serialize and deserialize TypeScript classes to JSON safely. What library?"},
    {"id": 417, "domain": "js_typescript", "text": "What npm package provides TypeScript support for algebraic data types?"},
    {"id": 418, "domain": "js_typescript", "text": "I need a library to do type-safe API client generation from OpenAPI specs for TypeScript."},
    {"id": 419, "domain": "js_typescript", "text": "What npm package provides TypeScript type checking for CSS modules?"},
    {"id": 420, "domain": "js_typescript", "text": "I want to enforce immutability on TypeScript objects at compile time. What library?"},
    {"id": 421, "domain": "js_typescript", "text": "What npm package provides TypeScript decorators for validation similar to Python's pydantic?"},
    {"id": 422, "domain": "js_typescript", "text": "I need a library for TypeScript that provides functional programming utilities (fp-ts alternative)."},
    {"id": 423, "domain": "js_typescript", "text": "What npm package provides TypeScript support for SQL query building with type safety?"},
    {"id": 424, "domain": "js_typescript", "text": "I want to auto-generate TypeScript interfaces from REST API responses. What library?"},
    {"id": 425, "domain": "js_typescript", "text": "What npm package provides type-safe routing for Express.js in TypeScript?"},
    {"id": 426, "domain": "js_typescript", "text": "I need a library to do structural typing enforcement in TypeScript at runtime."},
    {"id": 427, "domain": "js_typescript", "text": "What npm package provides TypeScript type inference for Redux state management?"},
    {"id": 428, "domain": "js_typescript", "text": "I want to generate mock data from TypeScript interfaces automatically. What library?"},
    {"id": 429, "domain": "js_typescript", "text": "What npm package provides TypeScript plugin for auto-completing CSS class names?"},
    {"id": 430, "domain": "js_typescript", "text": "I need a library for TypeScript that enforces domain-driven design patterns."},

    # ──────────────────────────────────────────────
    # 13. Cross-domain / Framework Integrations (35개)
    # ──────────────────────────────────────────────
    {"id": 431, "domain": "cross_domain", "text": "What package connects a FastAPI backend to a Next.js frontend with automatic type sharing?"},
    {"id": 432, "domain": "cross_domain", "text": "I need a library to sync data between a Django app and a React frontend in real-time."},
    {"id": 433, "domain": "cross_domain", "text": "What pip package integrates Celery with FastAPI for background task queuing?"},
    {"id": 434, "domain": "cross_domain", "text": "I want to use Redis Streams with a Python consumer and JavaScript producer. What libraries?"},
    {"id": 435, "domain": "cross_domain", "text": "What package provides GraphQL federation between a Python and a Node.js service?"},
    {"id": 436, "domain": "cross_domain", "text": "I need a library that synchronizes SQLAlchemy models between Python and TypeScript types."},
    {"id": 437, "domain": "cross_domain", "text": "What pip package integrates pytest with GitHub Actions for test reporting?"},
    {"id": 438, "domain": "cross_domain", "text": "I want to share OpenAPI specs between FastAPI and NestJS. What library?"},
    {"id": 439, "domain": "cross_domain", "text": "What package provides distributed session management for a Flask and Express.js app?"},
    {"id": 440, "domain": "cross_domain", "text": "I need a library to do server-sent events from Django to a React frontend."},
    {"id": 441, "domain": "cross_domain", "text": "What pip package provides Django integration with Elasticsearch for search?"},
    {"id": 442, "domain": "cross_domain", "text": "I want to use Prisma ORM from a FastAPI application. What library bridges them?"},
    {"id": 443, "domain": "cross_domain", "text": "What npm package provides type-safe gRPC clients for both TypeScript and Python?"},
    {"id": 444, "domain": "cross_domain", "text": "I need a library to integrate Stripe webhooks with both Flask and Express.js."},
    {"id": 445, "domain": "cross_domain", "text": "What package allows Django REST Framework to serve a React app with SSR?"},
    {"id": 446, "domain": "cross_domain", "text": "I want to do A/B testing across Python and JavaScript services. What library?"},
    {"id": 447, "domain": "cross_domain", "text": "What pip package provides Django integration with AWS Cognito authentication?"},
    {"id": 448, "domain": "cross_domain", "text": "I need a library to convert between Python dataclasses and TypeScript interfaces."},
    {"id": 449, "domain": "cross_domain", "text": "What package provides bidirectional data sync between MongoDB and PostgreSQL?"},
    {"id": 450, "domain": "cross_domain", "text": "I want to generate both Python and TypeScript clients from the same Protobuf definition."},
    {"id": 451, "domain": "cross_domain", "text": "What npm package provides React integration with PyScript for running Python in browsers?"},
    {"id": 452, "domain": "cross_domain", "text": "I need a library that integrates FastAPI with a Vue.js frontend for file uploads."},
    {"id": 453, "domain": "cross_domain", "text": "What package provides Flask integration with Socket.IO for real-time communication?"},
    {"id": 454, "domain": "cross_domain", "text": "I want to share validation rules between a Pydantic model and a Zod schema. What library?"},
    {"id": 455, "domain": "cross_domain", "text": "What pip package provides Django integration with Next.js for hybrid rendering?"},
    {"id": 456, "domain": "cross_domain", "text": "I need a library to serialize Django models to both JSON and MessagePack."},
    {"id": 457, "domain": "cross_domain", "text": "What package provides unified logging across Python and Node.js microservices?"},
    {"id": 458, "domain": "cross_domain", "text": "I want to do feature flags that work across both Python and JavaScript services. What library?"},
    {"id": 459, "domain": "cross_domain", "text": "What npm package integrates React with a FastAPI WebSocket endpoint automatically?"},
    {"id": 460, "domain": "cross_domain", "text": "I need a library to manage database migrations across both Python and Node.js services."},
    {"id": 461, "domain": "cross_domain", "text": "What package provides end-to-end type safety between a FastAPI backend and React frontend?"},
    {"id": 462, "domain": "cross_domain", "text": "I want to integrate Temporal.io workflows with both Python and JavaScript. What SDKs?"},
    {"id": 463, "domain": "cross_domain", "text": "What library provides unified error tracking across Python and JavaScript microservices?"},
    {"id": 464, "domain": "cross_domain", "text": "I need a package to convert SQLAlchemy models to TypeScript interfaces automatically."},
    {"id": 465, "domain": "cross_domain", "text": "What library integrates Kafka with both FastAPI consumers and Next.js producers?"},

    # ──────────────────────────────────────────────
    # 14. Niche / Specific Use Cases (35개)
    # ──────────────────────────────────────────────
    {"id": 466, "domain": "niche", "text": "What Python package integrates PyTorch with Neo4j for graph neural network training?"},
    {"id": 467, "domain": "niche", "text": "I need a library to process PDF tables with complex merged cells into pandas DataFrames."},
    {"id": 468, "domain": "niche", "text": "What npm package provides React components for visualizing AST (Abstract Syntax Trees)?"},
    {"id": 469, "domain": "niche", "text": "I want to do audio fingerprinting in Python to identify songs. What library?"},
    {"id": 470, "domain": "niche", "text": "What Python package converts Jupyter notebooks to production-ready Python scripts?"},
    {"id": 471, "domain": "niche", "text": "I need a library to do symbolic math computation integrated with NumPy arrays."},
    {"id": 472, "domain": "niche", "text": "What npm package provides React integration with TensorFlow.js for in-browser ML?"},
    {"id": 473, "domain": "niche", "text": "I want to process and analyze PCAP network capture files in Python. What library?"},
    {"id": 474, "domain": "niche", "text": "What Python package provides tools for Byzantine fault-tolerant distributed systems?"},
    {"id": 475, "domain": "niche", "text": "I need a library to parse and validate YAML with strict schema in Python."},
    {"id": 476, "domain": "niche", "text": "What npm package provides isomorphic rendering for Web Components in Next.js?"},
    {"id": 477, "domain": "niche", "text": "I want to do protein structure prediction in Python beyond AlphaFold. What library?"},
    {"id": 478, "domain": "niche", "text": "What Python package provides tools for DNA sequence analysis and alignment?"},
    {"id": 479, "domain": "niche", "text": "I need a library to do 3D point cloud processing in Python."},
    {"id": 480, "domain": "niche", "text": "What npm package provides React components for financial charting (candlestick, etc.)?"},
    {"id": 481, "domain": "niche", "text": "I want to process and analyze satellite imagery in Python. What library?"},
    {"id": 482, "domain": "niche", "text": "What Python package provides tools for smart contract interaction with Ethereum?"},
    {"id": 483, "domain": "niche", "text": "I need a library to parse and process MIDI files in Python."},
    {"id": 484, "domain": "niche", "text": "What npm package provides React components for building flowchart diagrams?"},
    {"id": 485, "domain": "niche", "text": "I want to do machine translation without using the Hugging Face API. What Python library?"},
    {"id": 486, "domain": "niche", "text": "What Python package provides tools for analyzing and visualizing graph networks?"},
    {"id": 487, "domain": "niche", "text": "I need a library to do optical character recognition (OCR) on scanned documents in Python."},
    {"id": 488, "domain": "niche", "text": "What npm package provides React Native integration with CoreML for iOS on-device ML?"},
    {"id": 489, "domain": "niche", "text": "I want to process and analyze EEG brain signals in Python. What library?"},
    {"id": 490, "domain": "niche", "text": "What Python package provides tools for working with astronomical data (FITS files)?"},
    {"id": 491, "domain": "niche", "text": "I need a library to do fluid dynamics simulation in Python."},
    {"id": 492, "domain": "niche", "text": "What npm package provides WebAssembly integration with React components?"},
    {"id": 493, "domain": "niche", "text": "I want to do game theory simulations in Python. What library?"},
    {"id": 494, "domain": "niche", "text": "What Python package provides tools for parsing and generating LATEX documents?"},
    {"id": 495, "domain": "niche", "text": "I need a library for generating music with neural networks in Python."},
    {"id": 496, "domain": "niche", "text": "What npm package provides React integration with WebGPU for GPU computing?"},
    {"id": 497, "domain": "niche", "text": "I want to process LiDAR point cloud data in Python for autonomous vehicles. What library?"},
    {"id": 498, "domain": "niche", "text": "What Python package provides tools for quantum computing simulation?"},
    {"id": 499, "domain": "niche", "text": "I need a library to build knowledge graphs from unstructured text in Python."},
    {"id": 500, "domain": "niche", "text": "What npm package provides React components for augmented reality (AR) experiences in browsers?"},
]

# 도메인별 통계
DOMAIN_STATS = {
    domain: len([q for q in QUESTIONS if q["domain"] == domain])
    for domain in set(q["domain"] for q in QUESTIONS)
}

# 도메인 한글 이름
DOMAIN_NAMES = {
    "python_ml":       "Python ML/딥러닝",
    "python_data":     "Python 데이터 처리",
    "python_web":      "Python 웹/API",
    "python_db":       "Python 데이터베이스",
    "python_devops":   "Python DevOps/클라우드",
    "python_security": "Python 보안/인증",
    "python_testing":  "Python 테스팅",
    "python_cli":      "Python CLI/유틸리티",
    "js_react":        "JavaScript React",
    "js_node":         "JavaScript Node.js",
    "js_testing":      "JavaScript 테스팅/빌드",
    "js_typescript":   "JavaScript TypeScript",
    "cross_domain":    "크로스 도메인",
    "niche":           "틈새/특수 분야",
}
